version: '2'
services:
  tests:
    build: .
    depends_on:
      - db
    environment:
      TEST_DATABASE_URL: postgres://postgres:null@db/test_db
    entrypoint: python tests.py
  db:
    image: postgres:9.6.0
    environment:
      POSTGRES_PASSWORD: null
      POSTGRES_DB: test_db
